### ISSUE TITLE
Error while building SEA++ on Ubuntu 14.0.4 and Ubuntu 16.0.4

### ISSUE THREAD

**Issue by parry816** [seapp/seapp_stable#1]
Hi, 
I tried to build SEA++ on Ubuntu, but "make" command fails with following error:
make[1]: Entering directory '/home/user/seapp_stable/src'
globalfilter/GlobalFilter.cc
In file included from /usr/include/libxml++-2.6/libxml++/exceptions/internal_error.h:25:0,
                 from /usr/include/libxml++-2.6/libxml++/libxml++.h:50,
                 from parser/Parser.h:16,
                 from globalfilter/GlobalFilter.cc:10:
/usr/include/libxml++-2.6/libxml++/exceptions/exception.h:26:28: fatal error: libxml++config.h: No such file or directory
compilation terminated.
Makefile:1089: recipe for target 'out/gcc-debug//globalfilter/GlobalFilter.o' failed
make[1]: *** [out/gcc-debug//globalfilter/GlobalFilter.o] Error 1
make[1]: Leaving directory '/home/gowher/seapp_stable/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
I am using Omnet++ 4.6. I installed all dependencies including libxml. Any suggestion?

**Comment by 179416326** [comment]
Have u sloved the problem? i am facing another one:
zz@zz-virtual-machine:~/omnetpp-5.5.1/samples/seapp_stable$ make
cd src && make
make[1]: Entering directory '/home/zz/omnetpp-5.5.1/samples/seapp_stable/src'
actions/actionbase/ActionBase.cc
In file included from actions/actionbase/ActionBase.cc:9:
actions/actionbase/ActionBase.h:19:10: fatal error: 'INETDefs.h' file not found
#include "INETDefs.h"

**Comment by seapp** [comment]
Hi,

currently SEA++ works on OMNeT++ 4.x only. 
It has not been ported on OMNeT++ 5.x, yet.
I'd suggest to use it with OMNeT++ 4.6.

/Francesco
